---
namespace: "ph_openshift_monorepo_example"
name: "automation"
version: "1.0.0"
readme: README.md
authors:
  - "prakhar1985 <psrivast@redhat.com>"
description: "Starter collection for this project's custom Ansible automation."
license: []
repository: "https://github.com/rhpds/ph-openshift-monorepo-example"
