#SPDX-License-Identifier: MIT-0
---
# tasks file for create_users

- name: Create lab users
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ create_users_password | password_hash('sha512') }}"
    state: present
    shell: /bin/bash
    create_home: true
  loop: "{{ create_users_users }}"
  loop_control:
    label: "{{ item }}"
  no_log: true
