#SPDX-License-Identifier: MIT-0
---
# tasks file for create_namespace

- name: Create OpenShift namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ create_namespace_name }}"
